services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    environment:
      PORT: "8080"
      MATCH_SEED: "123456789"
      MATCH_MAP: "canyon_clash"
    ports:
      - "8080:8080"

  client:
    build:
      context: ..
      dockerfile: docker/Dockerfile.client
    ports:
      - "8000:80"
    depends_on:
      - server
