/* This file is generated by scripts/build-assets.mjs. Do not edit. */
export const PRODUCTION_ATLAS_URL = '/assets/generated/iron-pass.json' as const;
export const PRODUCTION_ASSET_IDS = [] as const;
export type ProductionAssetId = (typeof PRODUCTION_ASSET_IDS)[number];
export const PRODUCTION_FRAME_IDS = ['technical.registration.idle.south.0'] as const;
export type ProductionFrameId = (typeof PRODUCTION_FRAME_IDS)[number];
