/* This file is generated by scripts/build-assets.mjs. Do not edit. */
export const PRODUCTION_ATLAS_URL = '/assets/generated/iron-pass.json' as const;
export const PRODUCTION_ASSET_IDS = ['unit.tank'] as const;
export type ProductionAssetId = (typeof PRODUCTION_ASSET_IDS)[number];
export const PRODUCTION_FRAME_IDS = [
  'technical.registration.idle.south.0',
  'unit.tank.idle.e.0',
  'unit.tank.idle.ese.0',
  'unit.tank.idle.se.0',
  'unit.tank.idle.sse.0',
  'unit.tank.idle.s.0',
  'unit.tank.idle.ssw.0',
  'unit.tank.idle.sw.0',
  'unit.tank.idle.wsw.0',
  'unit.tank.idle.w.0',
  'unit.tank.idle.wnw.0',
  'unit.tank.idle.nw.0',
  'unit.tank.idle.nnw.0',
  'unit.tank.idle.n.0',
  'unit.tank.idle.nne.0',
  'unit.tank.idle.ne.0',
  'unit.tank.idle.ene.0',
] as const;
export type ProductionFrameId = (typeof PRODUCTION_FRAME_IDS)[number];
